import slide from "../../../images/slide.webp";
export let SlideData = [
  {
    image: slide,
    title: "BUY AMBIEN ONLINE",
    name: "Tramadol 100mg",
    price: "150",
    sold_item: "45",
    link: "#",
  },
  {
    image: slide,
    title: "BUY AMBIEN ONLINE",
    name: "Tramadol 100mg",
    price: "150",
    sold_item: "45",
    link: "#",
    id: 2,
  },
  {
    image: slide,
    title: "BUY AMBIEN ONLINE",
    name: "Tramadol 100mg",
    price: "150",
    sold_item: "45",
    link: "#",
    id: 3,
  },
  {
    image: slide,
    title: "BUY AMBIEN ONLINE",
    name: "Tramadol 100mg",
    price: "150",
    sold_item: "45",
    link: "#",
    id: 4,
  },
  {
    image: slide,
    title: "BUY AMBIEN ONLINE",
    name: "Tramadol 100mg",
    price: "150",
    sold_item: "45",
    link: "#",
    id: 5,
  },
];
